// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.22.3
// source: hippocampus.proto

package contract

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hippocampus_Purge_FullMethodName                      = "/hippocampus.v1.Hippocampus/Purge"
	Hippocampus_Sleep_FullMethodName                      = "/hippocampus.v1.Hippocampus/Sleep"
	Hippocampus_PreviewConsolidation_FullMethodName       = "/hippocampus.v1.Hippocampus/PreviewConsolidation"
	Hippocampus_ExplainConsolidation_FullMethodName       = "/hippocampus.v1.Hippocampus/ExplainConsolidation"
	Hippocampus_WhoAmI_FullMethodName                     = "/hippocampus.v1.Hippocampus/WhoAmI"
	Hippocampus_StoreEvent_FullMethodName                 = "/hippocampus.v1.Hippocampus/StoreEvent"
	Hippocampus_EndEvent_FullMethodName                   = "/hippocampus.v1.Hippocampus/EndEvent"
	Hippocampus_UpdateEventSignificance_FullMethodName    = "/hippocampus.v1.Hippocampus/UpdateEventSignificance"
	Hippocampus_MergeEvents_FullMethodName                = "/hippocampus.v1.Hippocampus/MergeEvents"
	Hippocampus_DeleteEvent_FullMethodName                = "/hippocampus.v1.Hippocampus/DeleteEvent"
	Hippocampus_GetEventById_FullMethodName               = "/hippocampus.v1.Hippocampus/GetEventById"
	Hippocampus_GetEvents_FullMethodName                  = "/hippocampus.v1.Hippocampus/GetEvents"
	Hippocampus_StoreMemory_FullMethodName                = "/hippocampus.v1.Hippocampus/StoreMemory"
	Hippocampus_UpdateMemory_FullMethodName               = "/hippocampus.v1.Hippocampus/UpdateMemory"
	Hippocampus_DeleteMemories_FullMethodName             = "/hippocampus.v1.Hippocampus/DeleteMemories"
	Hippocampus_GetMemories_FullMethodName                = "/hippocampus.v1.Hippocampus/GetMemories"
	Hippocampus_RecallMemories_FullMethodName             = "/hippocampus.v1.Hippocampus/RecallMemories"
	Hippocampus_SearchMemories_FullMethodName             = "/hippocampus.v1.Hippocampus/SearchMemories"
	Hippocampus_ReplaceMemoriesWithSummary_FullMethodName = "/hippocampus.v1.Hippocampus/ReplaceMemoriesWithSummary"
	Hippocampus_GetSummarisationCandidates_FullMethodName = "/hippocampus.v1.Hippocampus/GetSummarisationCandidates"
	Hippocampus_SummariseMemories_FullMethodName          = "/hippocampus.v1.Hippocampus/SummariseMemories"
	Hippocampus_Export_FullMethodName                     = "/hippocampus.v1.Hippocampus/Export"
	Hippocampus_Import_FullMethodName                     = "/hippocampus.v1.Hippocampus/Import"
	Hippocampus_ImportBatch_FullMethodName                = "/hippocampus.v1.Hippocampus/ImportBatch"
	Hippocampus_Transfer_FullMethodName                   = "/hippocampus.v1.Hippocampus/Transfer"
	Hippocampus_Clear_FullMethodName                      = "/hippocampus.v1.Hippocampus/Clear"
)

// HippocampusClient is the client API for Hippocampus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HTTP annotations below map every RPC onto a REST-ish JSON endpoint under /v1, served by the
// grpc-gateway alongside the native gRPC API. Path-bound fields (e.g. {id}) are taken from the
// URL; for GET/DELETE the remaining fields are taken from the query string, and for POST/PATCH
// they are taken from the JSON body.
type HippocampusClient interface {
	// Purge deletes every event and memory in the store. While it runs, all other Hippocampus RPCs
	// are rejected with Unavailable.
	Purge(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	// Sleep manually triggers a consolidation cycle out of schedule and resets the periodic timer.
	// Rejected with FailedPrecondition on a read/write replica (consolidation.enabled: false),
	// which must never run its own cycle.
	Sleep(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	// PreviewConsolidation reports what a consolidation cycle would forget if one ran now, and
	// deletes nothing. It is the dry run for Sleep: the same decision rules, applied to the same
	// store, with the outcome returned instead of applied. Rejected with FailedPrecondition on a
	// read/write replica (consolidation.enabled: false), which never runs a cycle of its own and so
	// has nothing to preview.
	//
	// It is a separate RPC rather than a flag on Sleep so that the two can be authorised
	// separately - previewing what would be forgotten is a read, triggering it is not.
	PreviewConsolidation(ctx context.Context, in *PreviewConsolidationRequest, opts ...grpc.CallOption) (*PreviewConsolidationResponse, error)
	// ExplainConsolidation reports where individual memories stand against the consolidation rules -
	// each one's computed value, the threshold it is measured against, and how long it has before it
	// crosses - together with the capacity pressure scaling that threshold and, optionally, the decay
	// curve the configured algorithm produces. It reads nothing but the memories named in the
	// request and deletes nothing.
	//
	// Where PreviewConsolidation answers "what would a cycle forget now" across the whole store,
	// this answers "where does this memory stand, and when is it due" for memories the caller
	// already has in hand - which is why it needs only the reader tier: it enumerates nothing.
	// Rejected with FailedPrecondition on a read/write replica (consolidation.enabled: false),
	// whose configuration is not the one its store is consolidated under.
	ExplainConsolidation(ctx context.Context, in *ExplainConsolidationRequest, opts ...grpc.CallOption) (*ExplainConsolidationResponse, error)
	// WhoAmI reports the authenticated caller's identity and effective authorization tier
	// (reader/writer/admin), so a client - the web console - can tailor what it offers instead of
	// guessing at the token's roles. Requires only the reader tier. When the service runs without
	// authentication it reports auth_enabled false and an unrestricted (admin) tier.
	WhoAmI(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error)
	// Events
	// StoreEvent creates an event, optionally with nested memories (each defaulted to the new
	// event's id when unset). An event below event.minimumSignificance is quietly dropped - see
	// StoreEventResponse.
	StoreEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*StoreEventResponse, error)
	// EndEvent sets an event's time_end (defaults to now when unset). NotFound if the event does
	// not exist.
	EndEvent(ctx context.Context, in *EndEventRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	// UpdateEventSignificance changes an event's significance, either as an absolute value or via
	// placement (see SignificancePlacement). NotFound if the event does not exist.
	UpdateEventSignificance(ctx context.Context, in *UpdateEventSignificanceRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	// MergeEvents re-points every memory of merge_from onto merge_to. merge_to must already exist;
	// merge_from need not - an absent one simply matches no memories.
	MergeEvents(ctx context.Context, in *MergeEventsRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	// DeleteEvent deletes an event. When memories is true its memories are deleted too; otherwise
	// they are kept but detached (their event_id is cleared). NotFound if the event does not exist.
	DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	// GetEventById fetches a single event by id; set memories to also load its nested memories.
	// NotFound if the event does not exist.
	GetEventById(ctx context.Context, in *GetEventByIdRequest, opts ...grpc.CallOption) (*GetEventResponse, error)
	// GetEvents lists events filtered by time range, significance range, and group, paginated by
	// limit/offset (see GetEventsRequest). significance_extremum swaps the significance_min/max
	// range for "only events tied at the highest (or lowest) significance value" instead.
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
	// Memories
	// StoreMemory creates a memory. A memory below memory.minimumSignificance is quietly dropped -
	// see StoreMemoryResponse.
	StoreMemory(ctx context.Context, in *Memory, opts ...grpc.CallOption) (*StoreMemoryResponse, error)
	// UpdateMemory applies a partial update to an existing memory: only the fields carrying a value
	// (significance, body, event_id, group, time_stamp) overwrite the stored row. is_binary and
	// is_summary are NOT updatable here - they are set at creation and by ReplaceMemoriesWithSummary
	// - so any updated content must stay consistent with the memory's existing is_binary/is_summary:
	// a non-binary memory is re-indexed for content search, so its new body must remain valid text,
	// and a summary memory should keep summary-appropriate content. An unknown id returns NotFound
	// (no memory is created).
	UpdateMemory(ctx context.Context, in *Memory, opts ...grpc.CallOption) (*GeneralResponse, error)
	// DeleteMemories deletes the given memories by id; unknown ids are silently ignored.
	DeleteMemories(ctx context.Context, in *DeleteMemoriesRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	// GetMemories lists memories filtered by time range, significance range, and group, paginated
	// by limit/offset (see GetMemoriesRequest). significance_extremum swaps the significance_min/max
	// range for "only memories tied at the highest (or lowest) significance value" instead.
	GetMemories(ctx context.Context, in *GetMemoriesRequest, opts ...grpc.CallOption) (*GetMemoriesResponse, error)
	// RecallMemories returns the requested memories and reinforces each one: its recall time is
	// reset to now (resetting its decay clock) and its recall count is incremented (raising its
	// effective significance during consolidation). A reader-tier caller for whom reinforcement is
	// disabled (auth.readerRecallReinforces) gets a plain, non-reinforcing read instead; writer and
	// admin callers always reinforce.
	RecallMemories(ctx context.Context, in *RecallMemoriesRequest, opts ...grpc.CallOption) (*GetMemoriesResponse, error)
	// SearchMemories finds memories via the optional content-search index; see
	// SearchMemoriesRequest.
	SearchMemories(ctx context.Context, in *SearchMemoriesRequest, opts ...grpc.CallOption) (*GetMemoriesResponse, error)
	// Summarisation
	// ReplaceMemoriesWithSummary deletes every memory of an event and replaces them with a single
	// caller-supplied summary memory, in one transaction; see ReplaceMemoriesWithSummaryRequest.
	ReplaceMemoriesWithSummary(ctx context.Context, in *ReplaceMemoriesWithSummaryRequest, opts ...grpc.CallOption) (*ReplaceMemoriesWithSummaryResponse, error)
	// GetSummarisationCandidates returns events identified by the most recent sleep cycle as having
	// accumulated enough quiet, unsummarised memories to be worth condensing via
	// ReplaceMemoriesWithSummary. A point-in-time snapshot, refreshed only when
	// consolidation.summarisationMinMemories is configured.
	GetSummarisationCandidates(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetSummarisationCandidatesResponse, error)
	// SummariseMemories condenses an event's memories into a single summary using the optional
	// embedded LLM (ollama.enabled), then replaces them with it exactly as ReplaceMemoriesWithSummary
	// does - so the service generates the summary the caller would otherwise have to supply. Fails
	// with FAILED_PRECONDITION when no summariser is configured. See SummariseMemoriesRequest.
	SummariseMemories(ctx context.Context, in *SummariseMemoriesRequest, opts ...grpc.CallOption) (*SummariseMemoriesResponse, error)
	// Transfer and archive (embedded -> centralised)
	// Export snapshots the whole store into an archive object in S3 and records a manifest of
	// exactly what was captured; with clear set, the captured records are deleted once the upload
	// has succeeded.
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	// Import streams an archive object from S3 into the store, upserting every record by id with
	// its full state preserved. Idempotent; aborts on the first error.
	Import(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*ImportResponse, error)
	// ImportBatch upserts full-state rows by id directly - the ingest half of Transfer. Nothing is
	// defaulted or gated on minimum significance; the rows carry their history.
	ImportBatch(ctx context.Context, in *ImportBatchRequest, opts ...grpc.CallOption) (*ImportBatchResponse, error)
	// Transfer streams the whole store directly into a centralised instance's ImportBatch RPC,
	// recording a manifest like Export; with clear set the captured records are deleted once the
	// target has accepted every batch.
	Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	// Clear deletes exactly the records captured by the Export/Transfer run that produced the
	// manifest. Memories recalled (or re-created) since the capture survive, as do events that
	// still have memories.
	Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error)
}

type hippocampusClient struct {
	cc grpc.ClientConnInterface
}

func NewHippocampusClient(cc grpc.ClientConnInterface) HippocampusClient {
	return &hippocampusClient{cc}
}

func (c *hippocampusClient) Purge(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, Hippocampus_Purge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) Sleep(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, Hippocampus_Sleep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) PreviewConsolidation(ctx context.Context, in *PreviewConsolidationRequest, opts ...grpc.CallOption) (*PreviewConsolidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewConsolidationResponse)
	err := c.cc.Invoke(ctx, Hippocampus_PreviewConsolidation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) ExplainConsolidation(ctx context.Context, in *ExplainConsolidationRequest, opts ...grpc.CallOption) (*ExplainConsolidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainConsolidationResponse)
	err := c.cc.Invoke(ctx, Hippocampus_ExplainConsolidation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) WhoAmI(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhoAmIResponse)
	err := c.cc.Invoke(ctx, Hippocampus_WhoAmI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) StoreEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*StoreEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreEventResponse)
	err := c.cc.Invoke(ctx, Hippocampus_StoreEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) EndEvent(ctx context.Context, in *EndEventRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, Hippocampus_EndEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) UpdateEventSignificance(ctx context.Context, in *UpdateEventSignificanceRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, Hippocampus_UpdateEventSignificance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) MergeEvents(ctx context.Context, in *MergeEventsRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, Hippocampus_MergeEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, Hippocampus_DeleteEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) GetEventById(ctx context.Context, in *GetEventByIdRequest, opts ...grpc.CallOption) (*GetEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventResponse)
	err := c.cc.Invoke(ctx, Hippocampus_GetEventById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, Hippocampus_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) StoreMemory(ctx context.Context, in *Memory, opts ...grpc.CallOption) (*StoreMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreMemoryResponse)
	err := c.cc.Invoke(ctx, Hippocampus_StoreMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) UpdateMemory(ctx context.Context, in *Memory, opts ...grpc.CallOption) (*GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, Hippocampus_UpdateMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) DeleteMemories(ctx context.Context, in *DeleteMemoriesRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, Hippocampus_DeleteMemories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) GetMemories(ctx context.Context, in *GetMemoriesRequest, opts ...grpc.CallOption) (*GetMemoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemoriesResponse)
	err := c.cc.Invoke(ctx, Hippocampus_GetMemories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) RecallMemories(ctx context.Context, in *RecallMemoriesRequest, opts ...grpc.CallOption) (*GetMemoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemoriesResponse)
	err := c.cc.Invoke(ctx, Hippocampus_RecallMemories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) SearchMemories(ctx context.Context, in *SearchMemoriesRequest, opts ...grpc.CallOption) (*GetMemoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemoriesResponse)
	err := c.cc.Invoke(ctx, Hippocampus_SearchMemories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) ReplaceMemoriesWithSummary(ctx context.Context, in *ReplaceMemoriesWithSummaryRequest, opts ...grpc.CallOption) (*ReplaceMemoriesWithSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplaceMemoriesWithSummaryResponse)
	err := c.cc.Invoke(ctx, Hippocampus_ReplaceMemoriesWithSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) GetSummarisationCandidates(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GetSummarisationCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSummarisationCandidatesResponse)
	err := c.cc.Invoke(ctx, Hippocampus_GetSummarisationCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) SummariseMemories(ctx context.Context, in *SummariseMemoriesRequest, opts ...grpc.CallOption) (*SummariseMemoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummariseMemoriesResponse)
	err := c.cc.Invoke(ctx, Hippocampus_SummariseMemories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, Hippocampus_Export_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) Import(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*ImportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportResponse)
	err := c.cc.Invoke(ctx, Hippocampus_Import_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) ImportBatch(ctx context.Context, in *ImportBatchRequest, opts ...grpc.CallOption) (*ImportBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportBatchResponse)
	err := c.cc.Invoke(ctx, Hippocampus_ImportBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, Hippocampus_Transfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hippocampusClient) Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearResponse)
	err := c.cc.Invoke(ctx, Hippocampus_Clear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HippocampusServer is the server API for Hippocampus service.
// All implementations must embed UnimplementedHippocampusServer
// for forward compatibility.
//
// HTTP annotations below map every RPC onto a REST-ish JSON endpoint under /v1, served by the
// grpc-gateway alongside the native gRPC API. Path-bound fields (e.g. {id}) are taken from the
// URL; for GET/DELETE the remaining fields are taken from the query string, and for POST/PATCH
// they are taken from the JSON body.
type HippocampusServer interface {
	// Purge deletes every event and memory in the store. While it runs, all other Hippocampus RPCs
	// are rejected with Unavailable.
	Purge(context.Context, *EmptyRequest) (*GeneralResponse, error)
	// Sleep manually triggers a consolidation cycle out of schedule and resets the periodic timer.
	// Rejected with FailedPrecondition on a read/write replica (consolidation.enabled: false),
	// which must never run its own cycle.
	Sleep(context.Context, *EmptyRequest) (*GeneralResponse, error)
	// PreviewConsolidation reports what a consolidation cycle would forget if one ran now, and
	// deletes nothing. It is the dry run for Sleep: the same decision rules, applied to the same
	// store, with the outcome returned instead of applied. Rejected with FailedPrecondition on a
	// read/write replica (consolidation.enabled: false), which never runs a cycle of its own and so
	// has nothing to preview.
	//
	// It is a separate RPC rather than a flag on Sleep so that the two can be authorised
	// separately - previewing what would be forgotten is a read, triggering it is not.
	PreviewConsolidation(context.Context, *PreviewConsolidationRequest) (*PreviewConsolidationResponse, error)
	// ExplainConsolidation reports where individual memories stand against the consolidation rules -
	// each one's computed value, the threshold it is measured against, and how long it has before it
	// crosses - together with the capacity pressure scaling that threshold and, optionally, the decay
	// curve the configured algorithm produces. It reads nothing but the memories named in the
	// request and deletes nothing.
	//
	// Where PreviewConsolidation answers "what would a cycle forget now" across the whole store,
	// this answers "where does this memory stand, and when is it due" for memories the caller
	// already has in hand - which is why it needs only the reader tier: it enumerates nothing.
	// Rejected with FailedPrecondition on a read/write replica (consolidation.enabled: false),
	// whose configuration is not the one its store is consolidated under.
	ExplainConsolidation(context.Context, *ExplainConsolidationRequest) (*ExplainConsolidationResponse, error)
	// WhoAmI reports the authenticated caller's identity and effective authorization tier
	// (reader/writer/admin), so a client - the web console - can tailor what it offers instead of
	// guessing at the token's roles. Requires only the reader tier. When the service runs without
	// authentication it reports auth_enabled false and an unrestricted (admin) tier.
	WhoAmI(context.Context, *EmptyRequest) (*WhoAmIResponse, error)
	// Events
	// StoreEvent creates an event, optionally with nested memories (each defaulted to the new
	// event's id when unset). An event below event.minimumSignificance is quietly dropped - see
	// StoreEventResponse.
	StoreEvent(context.Context, *Event) (*StoreEventResponse, error)
	// EndEvent sets an event's time_end (defaults to now when unset). NotFound if the event does
	// not exist.
	EndEvent(context.Context, *EndEventRequest) (*GeneralResponse, error)
	// UpdateEventSignificance changes an event's significance, either as an absolute value or via
	// placement (see SignificancePlacement). NotFound if the event does not exist.
	UpdateEventSignificance(context.Context, *UpdateEventSignificanceRequest) (*GeneralResponse, error)
	// MergeEvents re-points every memory of merge_from onto merge_to. merge_to must already exist;
	// merge_from need not - an absent one simply matches no memories.
	MergeEvents(context.Context, *MergeEventsRequest) (*GeneralResponse, error)
	// DeleteEvent deletes an event. When memories is true its memories are deleted too; otherwise
	// they are kept but detached (their event_id is cleared). NotFound if the event does not exist.
	DeleteEvent(context.Context, *DeleteEventRequest) (*GeneralResponse, error)
	// GetEventById fetches a single event by id; set memories to also load its nested memories.
	// NotFound if the event does not exist.
	GetEventById(context.Context, *GetEventByIdRequest) (*GetEventResponse, error)
	// GetEvents lists events filtered by time range, significance range, and group, paginated by
	// limit/offset (see GetEventsRequest). significance_extremum swaps the significance_min/max
	// range for "only events tied at the highest (or lowest) significance value" instead.
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	// Memories
	// StoreMemory creates a memory. A memory below memory.minimumSignificance is quietly dropped -
	// see StoreMemoryResponse.
	StoreMemory(context.Context, *Memory) (*StoreMemoryResponse, error)
	// UpdateMemory applies a partial update to an existing memory: only the fields carrying a value
	// (significance, body, event_id, group, time_stamp) overwrite the stored row. is_binary and
	// is_summary are NOT updatable here - they are set at creation and by ReplaceMemoriesWithSummary
	// - so any updated content must stay consistent with the memory's existing is_binary/is_summary:
	// a non-binary memory is re-indexed for content search, so its new body must remain valid text,
	// and a summary memory should keep summary-appropriate content. An unknown id returns NotFound
	// (no memory is created).
	UpdateMemory(context.Context, *Memory) (*GeneralResponse, error)
	// DeleteMemories deletes the given memories by id; unknown ids are silently ignored.
	DeleteMemories(context.Context, *DeleteMemoriesRequest) (*GeneralResponse, error)
	// GetMemories lists memories filtered by time range, significance range, and group, paginated
	// by limit/offset (see GetMemoriesRequest). significance_extremum swaps the significance_min/max
	// range for "only memories tied at the highest (or lowest) significance value" instead.
	GetMemories(context.Context, *GetMemoriesRequest) (*GetMemoriesResponse, error)
	// RecallMemories returns the requested memories and reinforces each one: its recall time is
	// reset to now (resetting its decay clock) and its recall count is incremented (raising its
	// effective significance during consolidation). A reader-tier caller for whom reinforcement is
	// disabled (auth.readerRecallReinforces) gets a plain, non-reinforcing read instead; writer and
	// admin callers always reinforce.
	RecallMemories(context.Context, *RecallMemoriesRequest) (*GetMemoriesResponse, error)
	// SearchMemories finds memories via the optional content-search index; see
	// SearchMemoriesRequest.
	SearchMemories(context.Context, *SearchMemoriesRequest) (*GetMemoriesResponse, error)
	// Summarisation
	// ReplaceMemoriesWithSummary deletes every memory of an event and replaces them with a single
	// caller-supplied summary memory, in one transaction; see ReplaceMemoriesWithSummaryRequest.
	ReplaceMemoriesWithSummary(context.Context, *ReplaceMemoriesWithSummaryRequest) (*ReplaceMemoriesWithSummaryResponse, error)
	// GetSummarisationCandidates returns events identified by the most recent sleep cycle as having
	// accumulated enough quiet, unsummarised memories to be worth condensing via
	// ReplaceMemoriesWithSummary. A point-in-time snapshot, refreshed only when
	// consolidation.summarisationMinMemories is configured.
	GetSummarisationCandidates(context.Context, *EmptyRequest) (*GetSummarisationCandidatesResponse, error)
	// SummariseMemories condenses an event's memories into a single summary using the optional
	// embedded LLM (ollama.enabled), then replaces them with it exactly as ReplaceMemoriesWithSummary
	// does - so the service generates the summary the caller would otherwise have to supply. Fails
	// with FAILED_PRECONDITION when no summariser is configured. See SummariseMemoriesRequest.
	SummariseMemories(context.Context, *SummariseMemoriesRequest) (*SummariseMemoriesResponse, error)
	// Transfer and archive (embedded -> centralised)
	// Export snapshots the whole store into an archive object in S3 and records a manifest of
	// exactly what was captured; with clear set, the captured records are deleted once the upload
	// has succeeded.
	Export(context.Context, *ExportRequest) (*ExportResponse, error)
	// Import streams an archive object from S3 into the store, upserting every record by id with
	// its full state preserved. Idempotent; aborts on the first error.
	Import(context.Context, *ImportRequest) (*ImportResponse, error)
	// ImportBatch upserts full-state rows by id directly - the ingest half of Transfer. Nothing is
	// defaulted or gated on minimum significance; the rows carry their history.
	ImportBatch(context.Context, *ImportBatchRequest) (*ImportBatchResponse, error)
	// Transfer streams the whole store directly into a centralised instance's ImportBatch RPC,
	// recording a manifest like Export; with clear set the captured records are deleted once the
	// target has accepted every batch.
	Transfer(context.Context, *TransferRequest) (*TransferResponse, error)
	// Clear deletes exactly the records captured by the Export/Transfer run that produced the
	// manifest. Memories recalled (or re-created) since the capture survive, as do events that
	// still have memories.
	Clear(context.Context, *ClearRequest) (*ClearResponse, error)
	mustEmbedUnimplementedHippocampusServer()
}

// UnimplementedHippocampusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHippocampusServer struct{}

func (UnimplementedHippocampusServer) Purge(context.Context, *EmptyRequest) (*GeneralResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Purge not implemented")
}
func (UnimplementedHippocampusServer) Sleep(context.Context, *EmptyRequest) (*GeneralResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sleep not implemented")
}
func (UnimplementedHippocampusServer) PreviewConsolidation(context.Context, *PreviewConsolidationRequest) (*PreviewConsolidationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewConsolidation not implemented")
}
func (UnimplementedHippocampusServer) ExplainConsolidation(context.Context, *ExplainConsolidationRequest) (*ExplainConsolidationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExplainConsolidation not implemented")
}
func (UnimplementedHippocampusServer) WhoAmI(context.Context, *EmptyRequest) (*WhoAmIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WhoAmI not implemented")
}
func (UnimplementedHippocampusServer) StoreEvent(context.Context, *Event) (*StoreEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreEvent not implemented")
}
func (UnimplementedHippocampusServer) EndEvent(context.Context, *EndEventRequest) (*GeneralResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndEvent not implemented")
}
func (UnimplementedHippocampusServer) UpdateEventSignificance(context.Context, *UpdateEventSignificanceRequest) (*GeneralResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEventSignificance not implemented")
}
func (UnimplementedHippocampusServer) MergeEvents(context.Context, *MergeEventsRequest) (*GeneralResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MergeEvents not implemented")
}
func (UnimplementedHippocampusServer) DeleteEvent(context.Context, *DeleteEventRequest) (*GeneralResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (UnimplementedHippocampusServer) GetEventById(context.Context, *GetEventByIdRequest) (*GetEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventById not implemented")
}
func (UnimplementedHippocampusServer) GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedHippocampusServer) StoreMemory(context.Context, *Memory) (*StoreMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreMemory not implemented")
}
func (UnimplementedHippocampusServer) UpdateMemory(context.Context, *Memory) (*GeneralResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMemory not implemented")
}
func (UnimplementedHippocampusServer) DeleteMemories(context.Context, *DeleteMemoriesRequest) (*GeneralResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMemories not implemented")
}
func (UnimplementedHippocampusServer) GetMemories(context.Context, *GetMemoriesRequest) (*GetMemoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemories not implemented")
}
func (UnimplementedHippocampusServer) RecallMemories(context.Context, *RecallMemoriesRequest) (*GetMemoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecallMemories not implemented")
}
func (UnimplementedHippocampusServer) SearchMemories(context.Context, *SearchMemoriesRequest) (*GetMemoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchMemories not implemented")
}
func (UnimplementedHippocampusServer) ReplaceMemoriesWithSummary(context.Context, *ReplaceMemoriesWithSummaryRequest) (*ReplaceMemoriesWithSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplaceMemoriesWithSummary not implemented")
}
func (UnimplementedHippocampusServer) GetSummarisationCandidates(context.Context, *EmptyRequest) (*GetSummarisationCandidatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSummarisationCandidates not implemented")
}
func (UnimplementedHippocampusServer) SummariseMemories(context.Context, *SummariseMemoriesRequest) (*SummariseMemoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SummariseMemories not implemented")
}
func (UnimplementedHippocampusServer) Export(context.Context, *ExportRequest) (*ExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedHippocampusServer) Import(context.Context, *ImportRequest) (*ImportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Import not implemented")
}
func (UnimplementedHippocampusServer) ImportBatch(context.Context, *ImportBatchRequest) (*ImportBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportBatch not implemented")
}
func (UnimplementedHippocampusServer) Transfer(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedHippocampusServer) Clear(context.Context, *ClearRequest) (*ClearResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Clear not implemented")
}
func (UnimplementedHippocampusServer) mustEmbedUnimplementedHippocampusServer() {}
func (UnimplementedHippocampusServer) testEmbeddedByValue()                     {}

// UnsafeHippocampusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HippocampusServer will
// result in compilation errors.
type UnsafeHippocampusServer interface {
	mustEmbedUnimplementedHippocampusServer()
}

func RegisterHippocampusServer(s grpc.ServiceRegistrar, srv HippocampusServer) {
	// If the following call panics, it indicates UnimplementedHippocampusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hippocampus_ServiceDesc, srv)
}

func _Hippocampus_Purge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).Purge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_Purge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).Purge(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_Sleep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).Sleep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_Sleep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).Sleep(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_PreviewConsolidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewConsolidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).PreviewConsolidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_PreviewConsolidation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).PreviewConsolidation(ctx, req.(*PreviewConsolidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_ExplainConsolidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainConsolidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).ExplainConsolidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_ExplainConsolidation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).ExplainConsolidation(ctx, req.(*ExplainConsolidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_WhoAmI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).WhoAmI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_WhoAmI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).WhoAmI(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_StoreEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).StoreEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_StoreEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).StoreEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_EndEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).EndEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_EndEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).EndEvent(ctx, req.(*EndEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_UpdateEventSignificance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventSignificanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).UpdateEventSignificance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_UpdateEventSignificance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).UpdateEventSignificance(ctx, req.(*UpdateEventSignificanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_MergeEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).MergeEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_MergeEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).MergeEvents(ctx, req.(*MergeEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_DeleteEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).DeleteEvent(ctx, req.(*DeleteEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_GetEventById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).GetEventById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_GetEventById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).GetEventById(ctx, req.(*GetEventByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_StoreMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Memory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).StoreMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_StoreMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).StoreMemory(ctx, req.(*Memory))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_UpdateMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Memory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).UpdateMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_UpdateMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).UpdateMemory(ctx, req.(*Memory))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_DeleteMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).DeleteMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_DeleteMemories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).DeleteMemories(ctx, req.(*DeleteMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_GetMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).GetMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_GetMemories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).GetMemories(ctx, req.(*GetMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_RecallMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecallMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).RecallMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_RecallMemories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).RecallMemories(ctx, req.(*RecallMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_SearchMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).SearchMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_SearchMemories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).SearchMemories(ctx, req.(*SearchMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_ReplaceMemoriesWithSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceMemoriesWithSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).ReplaceMemoriesWithSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_ReplaceMemoriesWithSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).ReplaceMemoriesWithSummary(ctx, req.(*ReplaceMemoriesWithSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_GetSummarisationCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).GetSummarisationCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_GetSummarisationCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).GetSummarisationCandidates(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_SummariseMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummariseMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).SummariseMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_SummariseMemories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).SummariseMemories(ctx, req.(*SummariseMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_Export_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).Export(ctx, req.(*ExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_Import_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).Import(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_Import_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).Import(ctx, req.(*ImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_ImportBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).ImportBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_ImportBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).ImportBatch(ctx, req.(*ImportBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_Transfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).Transfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hippocampus_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HippocampusServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hippocampus_Clear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HippocampusServer).Clear(ctx, req.(*ClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hippocampus_ServiceDesc is the grpc.ServiceDesc for Hippocampus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hippocampus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hippocampus.v1.Hippocampus",
	HandlerType: (*HippocampusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Purge",
			Handler:    _Hippocampus_Purge_Handler,
		},
		{
			MethodName: "Sleep",
			Handler:    _Hippocampus_Sleep_Handler,
		},
		{
			MethodName: "PreviewConsolidation",
			Handler:    _Hippocampus_PreviewConsolidation_Handler,
		},
		{
			MethodName: "ExplainConsolidation",
			Handler:    _Hippocampus_ExplainConsolidation_Handler,
		},
		{
			MethodName: "WhoAmI",
			Handler:    _Hippocampus_WhoAmI_Handler,
		},
		{
			MethodName: "StoreEvent",
			Handler:    _Hippocampus_StoreEvent_Handler,
		},
		{
			MethodName: "EndEvent",
			Handler:    _Hippocampus_EndEvent_Handler,
		},
		{
			MethodName: "UpdateEventSignificance",
			Handler:    _Hippocampus_UpdateEventSignificance_Handler,
		},
		{
			MethodName: "MergeEvents",
			Handler:    _Hippocampus_MergeEvents_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _Hippocampus_DeleteEvent_Handler,
		},
		{
			MethodName: "GetEventById",
			Handler:    _Hippocampus_GetEventById_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _Hippocampus_GetEvents_Handler,
		},
		{
			MethodName: "StoreMemory",
			Handler:    _Hippocampus_StoreMemory_Handler,
		},
		{
			MethodName: "UpdateMemory",
			Handler:    _Hippocampus_UpdateMemory_Handler,
		},
		{
			MethodName: "DeleteMemories",
			Handler:    _Hippocampus_DeleteMemories_Handler,
		},
		{
			MethodName: "GetMemories",
			Handler:    _Hippocampus_GetMemories_Handler,
		},
		{
			MethodName: "RecallMemories",
			Handler:    _Hippocampus_RecallMemories_Handler,
		},
		{
			MethodName: "SearchMemories",
			Handler:    _Hippocampus_SearchMemories_Handler,
		},
		{
			MethodName: "ReplaceMemoriesWithSummary",
			Handler:    _Hippocampus_ReplaceMemoriesWithSummary_Handler,
		},
		{
			MethodName: "GetSummarisationCandidates",
			Handler:    _Hippocampus_GetSummarisationCandidates_Handler,
		},
		{
			MethodName: "SummariseMemories",
			Handler:    _Hippocampus_SummariseMemories_Handler,
		},
		{
			MethodName: "Export",
			Handler:    _Hippocampus_Export_Handler,
		},
		{
			MethodName: "Import",
			Handler:    _Hippocampus_Import_Handler,
		},
		{
			MethodName: "ImportBatch",
			Handler:    _Hippocampus_ImportBatch_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _Hippocampus_Transfer_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _Hippocampus_Clear_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hippocampus.proto",
}
