-- generated by scripts/schema-fixtures.sh from v0.23.0 (ae5adbe) on 2026-08-19T03:07:13Z
-- one statement per line; replayed by db/schema_upgrade_test.go. Do not hand-edit.
CREATE TABLE `events` ( `id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `time_start` bigint NOT NULL DEFAULT '0', `time_end` bigint NOT NULL DEFAULT '0', `significance_level_id` bigint DEFAULT NULL, `name` text NOT NULL, `description` text NOT NULL, `memories_consolidated` tinyint(1) NOT NULL DEFAULT '0', `relationship_significance` bigint NOT NULL DEFAULT '0', `relationships` text NOT NULL, `group_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', PRIMARY KEY (`id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT INTO `events` VALUES ('evt-alpha',1767225600000000000,0,1,'alpha event','seeded fixture event',0,0,'[]','alpha');
INSERT INTO `events` VALUES ('evt-beta',1767484800000000000,1767571200000000000,5,'beta event','an ended event',0,0,'[]','beta');
CREATE TABLE `memories` ( `id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `timestamp` bigint NOT NULL DEFAULT '0', `significance_level_id` bigint DEFAULT NULL, `event_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', `is_binary` tinyint(1) NOT NULL DEFAULT '0', `time_recalled` bigint NOT NULL DEFAULT '0', `recall_count` int NOT NULL DEFAULT '0', `is_summary` tinyint(1) NOT NULL DEFAULT '0', `group_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '', `is_compressed` tinyint(1) NOT NULL DEFAULT '0', `body` longblob NOT NULL, PRIMARY KEY (`id`), KEY `idx_memories_consolidation` (`event_id`,`timestamp`,`significance_level_id`,`time_recalled`,`recall_count`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT INTO `memories` VALUES ('mem-alpha-1',1767225600000000000,2,'evt-alpha',0,0,0,0,'',0,_binary 'alpha one: the quick brown fox');
INSERT INTO `memories` VALUES ('mem-alpha-2',1767312000000000000,3,'evt-alpha',0,0,0,0,'',0,_binary 'alpha two: jumps over the lazy dog');
INSERT INTO `memories` VALUES ('mem-alpha-3',1767398400000000000,4,'evt-alpha',0,1787108833747800000,1,0,'',0,_binary 'alpha three: pack my box with five dozen liquor jugs');
INSERT INTO `memories` VALUES ('mem-beta-1',1767484800000000000,6,'evt-beta',0,0,0,0,'beta',0,_binary 'beta one: sphinx of black quartz judge my vow');
INSERT INTO `memories` VALUES ('mem-binary',1767830400000000000,9,'',1,0,0,0,'alpha',0,_binary 'YmluYXJ5IHBheWxvYWQ=');
INSERT INTO `memories` VALUES ('mem-long',1767916800000000000,10,'',0,0,0,0,'alpha',1,_binary 'ã\0\0\0\0\0ˇ\Ïñ¡C![y¸û4¢0£\‚ó§˙4\ÒèØ\Ïn™\‡\„\Î\\â∞:\’\€WéîXÜÃépåüh	Ñ/Iµ=êénª=H\Â\ÓÉ\˜¡!?\»S∫ÅÆd;∞•ûWX¯\0\0ˇˇ:•æ†\n\0\0');
INSERT INTO `memories` VALUES ('mem-loose-1',1767657600000000000,7,'',0,0,0,0,'alpha',0,_binary 'loose one: how vexingly quick daft zebras jump');
INSERT INTO `memories` VALUES ('mem-loose-2',1767744000000000000,8,'',0,0,0,0,'',0,_binary 'loose two: a low-significance memory that decay should reach first');
CREATE TABLE `significance_levels` ( `id` bigint NOT NULL AUTO_INCREMENT, `level_rank` int NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `level_rank` (`level_rank`) ) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT INTO `significance_levels` VALUES (8,10);
INSERT INTO `significance_levels` VALUES (3,20);
INSERT INTO `significance_levels` VALUES (5,30);
INSERT INTO `significance_levels` VALUES (6,40);
INSERT INTO `significance_levels` VALUES (9,45);
INSERT INTO `significance_levels` VALUES (2,50);
INSERT INTO `significance_levels` VALUES (10,55);
INSERT INTO `significance_levels` VALUES (1,60);
INSERT INTO `significance_levels` VALUES (7,70);
INSERT INTO `significance_levels` VALUES (4,80);
