package db

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	log "github.com/sirupsen/logrus"
)

// ErrInvalidPlacement wraps a significance-placement request that names a bad anchor (unknown id,
// unranked item, or upper bound not above the lower) - a client fault, so the RPC layer maps it to
// InvalidArgument rather than an internal error.
var ErrInvalidPlacement = errors.New("invalid significance placement")

// The significance registry.
//
// Significance is a single, visible integer on both memories and events, but a dense one: there is
// no room between two adjacent values. To let a client rank a new item "between" two existing
// values (or "just above"/"just below" an existing one), significance is stored indirectly: each
// distinct significance value is one row - a "level" - in significance_levels, carrying a stable id
// and its rank (the visible significance). Items reference a level by id
// (memories.significance_level_id / events.significance_level_id, NULL meaning unranked). Opening a
// gap between two values then renumbers only this small registry (one row per distinct value), and
// every item pointing at a bumped level follows automatically - so an insert never rewrites the
// (potentially millions of) item rows. One shared registry backs both tables: the value math adds
// event and memory significance, i.e. treats them as one scale.
//
// Ranks are non-negative and gaps are always opened upward (incrementing levels at or above the
// target slot), so significance never goes negative. A periodic compaction (compactSignificanceLevels)
// keeps ranks small and inside int32.

const (
	significanceLevelsTable = "significance_levels"
	coveringIndexName       = "idx_memories_consolidation"
	coveringIndexColumns    = "(event_id, timestamp, significance_level_id, time_recalled, recall_count)"
)

// significanceLevelsDDL is the CREATE TABLE for the registry in the active dialect. level_rank is UNIQUE
// so a value maps to exactly one level; id is an auto-assigned stable key items reference.
func (d *DB) significanceLevelsDDL() string {
	switch d.driver {

	case driverPostgres:
		return `CREATE TABLE IF NOT EXISTS significance_levels (
			id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			level_rank INTEGER NOT NULL UNIQUE
		)`

	case driverMySQL:
		return `CREATE TABLE IF NOT EXISTS significance_levels (
			id   BIGINT AUTO_INCREMENT PRIMARY KEY,
			level_rank INTEGER NOT NULL UNIQUE
		)`

	default:
		return `CREATE TABLE IF NOT EXISTS significance_levels (
			id   INTEGER PRIMARY KEY AUTOINCREMENT,
			level_rank INTEGER NOT NULL UNIQUE
		)`
	}
}

// columnExists reports whether a column is present on a table, driver-aware, using the same probes
// as addColumnIfMissing but returning the boolean so callers can branch (the significance migration
// guards on the old column still existing). Runs at init time on the bare handle.
func (d *DB) columnExists(table string, column string) (bool, error) {
	probe := `SELECT name FROM pragma_table_info(?) WHERE name = ?`

	switch d.driver {

	case driverPostgres:
		probe = `SELECT column_name FROM information_schema.columns
			WHERE table_schema = current_schema() AND table_name = ? AND column_name = ?`

	case driverMySQL:
		probe = `SELECT column_name FROM information_schema.columns
			WHERE table_schema = DATABASE() AND table_name = ? AND column_name = ?`
	}

	rows, err := d.sql.Query(d.rebind(probe), table, column)
	if err != nil {
		return false, err
	}

	exists := rows.Next()

	if err := rows.Err(); err != nil {
		_ = rows.Close()

		return false, err
	}

	_ = rows.Close()

	return exists, nil
}

// ensureCoveringIndex creates the memories consolidation covering index keyed on
// significance_level_id, idempotently, across dialects. The scans read only these columns, so they
// never touch the pages holding memory bodies.
func (d *DB) ensureCoveringIndex() error {
	log.Trace("func() db.ensureCoveringIndex")

	if d.driver == driverMySQL {
		return d.createMySQLIndexIfMissing(
			"memories",
			coveringIndexName,
			`CREATE INDEX `+coveringIndexName+` ON memories `+coveringIndexColumns,
		)
	}

	if _, err := d.sql.Exec(`CREATE INDEX IF NOT EXISTS ` + coveringIndexName + ` ON memories ` + coveringIndexColumns); err != nil {
		log.Errorf("failed to create covering index: %s", err.Error())

		return err
	}

	return nil
}

// dropCoveringIndex removes the covering index, idempotently. The migration must drop it before
// dropping the old significance column: SQLite refuses to drop an indexed column outright, and
// MySQL would silently reshape the index rather than fail.
func (d *DB) dropCoveringIndex() error {
	log.Trace("func() db.dropCoveringIndex")

	if d.driver == driverMySQL {
		var count int

		if err := d.sql.QueryRow(
			`SELECT COUNT(*) FROM information_schema.statistics
			WHERE table_schema = DATABASE() AND table_name = 'memories' AND index_name = ?`,
			coveringIndexName,
		).Scan(&count); err != nil {
			return err
		}

		if count == 0 {
			return nil
		}

		_, err := d.sql.Exec(`DROP INDEX ` + coveringIndexName + ` ON memories`)

		return err
	}

	_, err := d.sql.Exec(`DROP INDEX IF EXISTS ` + coveringIndexName)

	return err
}

// migrateSignificanceToLevels performs the one-time move from a per-item integer `significance`
// column to the registry: seed a level for every distinct significance value in use, backfill each
// memory/event's significance_level_id, then drop the old column. It is guarded on the old column
// still existing, so it is a no-op on a database created straight into the new shape and on every
// startup after the first. The significance_levels table and the significance_level_id columns must
// already exist (created by the schema/addColumn steps that run before this); the caller recreates
// the covering index afterward.
func (d *DB) migrateSignificanceToLevels() error {
	log.Trace("func() db.migrateSignificanceToLevels")

	exists, err := d.columnExists("memories", "significance")
	if err != nil {
		return err
	}

	if !exists {
		return nil
	}

	log.Info("migrating per-item significance to the significance registry")

	// Seed the registry with every distinct significance value in use (> 0; 0 is unranked and maps
	// to a NULL level). A UNION across both tables gives the shared set of ranks.
	seed := `INSERT INTO significance_levels (level_rank)
		SELECT r FROM (
			SELECT DISTINCT significance AS r FROM memories WHERE significance > 0
			UNION
			SELECT DISTINCT significance AS r FROM events WHERE significance > 0
		) AS distinct_ranks
		WHERE r NOT IN (SELECT level_rank FROM significance_levels)`

	if _, err := d.sql.Exec(seed); err != nil {
		log.Errorf("failed to seed significance registry: %s", err.Error())

		return err
	}

	for _, table := range []string{"memories", "events"} {
		backfill := `UPDATE ` + table + ` SET significance_level_id =
			(SELECT id FROM significance_levels WHERE level_rank = ` + table + `.significance)
			WHERE significance > 0`

		if _, err := d.sql.Exec(backfill); err != nil {
			log.Errorf("failed to backfill %s significance levels: %s", table, err.Error())

			return err
		}
	}

	if err := d.dropCoveringIndex(); err != nil {
		return err
	}

	for _, table := range []string{"memories", "events"} {
		if _, err := d.sql.Exec(`ALTER TABLE ` + table + ` DROP COLUMN significance`); err != nil {
			log.Errorf("failed to drop old significance column on %s: %s", table, err.Error())

			return err
		}
	}

	return nil
}

// loadSignificanceRanks reads the whole registry into a level-id -> rank map. The consolidation
// scans load one snapshot at the start of a cycle and translate each row's significance_level_id to
// its rank in Go, so the scans stay on the covering index (no join to significance_levels) and
// never read memory bodies. A NULL level id is unranked and resolves to rank 0.
func (d *DB) loadSignificanceRanks(ctx context.Context) (map[int64]int32, error) {
	log.Trace("func() db.loadSignificanceRanks")

	ctx, cancel := d.opContext(ctx)
	defer cancel()

	rows, err := d.query(ctx, `SELECT id, level_rank FROM significance_levels`)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	ranks := make(map[int64]int32)

	for rows.Next() {
		var (
			id   int64
			rank int32
		)

		if err := rows.Scan(&id, &rank); err != nil {
			return nil, err
		}

		ranks[id] = rank
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return ranks, nil
}

// rankOf resolves a level id (nullable) to its rank via a snapshot, defaulting an unranked or
// unknown level to 0 - so a scan translating rows never fails on a level created after the snapshot
// (it simply reads as unranked for that one cycle; order is otherwise preserved).
func rankOf(ranks map[int64]int32, levelID sql.NullInt64) int32 {
	if !levelID.Valid {
		return 0
	}

	return ranks[levelID.Int64]
}

// SignificanceSpec asks the registry to resolve a significance to a level id. It is either an
// absolute value (Placement none, Value the rank; 0 meaning unranked -> NULL level) or a relative
// placement (ABOVE/BELOW/BETWEEN an anchor, the anchor given by rank value or by an existing item's
// id whose rank is looked up). It is built at the RPC layer from the request's SignificancePlacement.
type SignificanceSpec struct {
	Placement SignificancePlacement

	// Value is the absolute significance when Placement is PlacementNone.
	Value int32

	// Anchor / Upper are placement anchors as rank values; AnchorID / UpperID name an existing item
	// instead, whose current rank is looked up. Upper/UpperID apply to BETWEEN only.
	Anchor   int32
	AnchorID string
	Upper    int32
	UpperID  string

	// AnchorKind / UpperKind name the table an *ID anchor refers to, so its rank can be looked up.
	AnchorKind AnchorKind
	UpperKind  AnchorKind
}

// SignificancePlacement mirrors contract.SignificancePlacement_Mode without the db package
// depending on the contract package.
type SignificancePlacement int

const (
	PlacementNone SignificancePlacement = iota
	PlacementAbove
	PlacementBelow
	PlacementBetween
)

// AnchorKind names which table an id-based placement anchor lives in.
type AnchorKind int

const (
	AnchorMemory AnchorKind = iota
	AnchorEvent
)

// ResolveSignificanceLevel returns the level id (nullable) to store on an item for the given spec,
// plus the resolved rank (0 when unranked), creating levels and opening gaps as needed. It runs in
// one transaction and, on the server drivers, under the registry advisory lock, so two concurrent
// writers cannot renumber at once. A NULL id means unranked.
func (d *DB) ResolveSignificanceLevel(ctx context.Context, spec SignificanceSpec) (sql.NullInt64, int32, error) {
	log.Trace("func() db.ResolveSignificanceLevel")

	if spec.Placement == PlacementNone {
		// Absolute unranked: nothing to resolve.
		if spec.Value <= 0 {
			return sql.NullInt64{}, 0, nil
		}

		// Fast path: a level for an already-known rank needs no lock, so ordinary writes (which
		// reuse existing ranks) never serialize on the registry lock - only creating a new rank or a
		// placement gap-open does.
		id, found, err := d.findLevel(ctx, spec.Value)
		if err != nil {
			return sql.NullInt64{}, 0, err
		}

		if found {
			return nullInt64(id), spec.Value, nil
		}
	}

	release, err := d.acquireRegistryLock(ctx)
	if err != nil {
		return sql.NullInt64{}, 0, err
	}
	defer release()

	tx, cancel, err := d.beginTx(ctx)
	if err != nil {
		return sql.NullInt64{}, 0, err
	}
	defer cancel()

	id, rank, err := d.resolveLevelTx(ctx, tx, spec)
	if err != nil {
		_ = tx.Rollback()

		return sql.NullInt64{}, 0, err
	}

	if err := tx.Commit(); err != nil {
		return sql.NullInt64{}, 0, err
	}

	return id, rank, nil
}

// resolveLevelTx computes the target rank for the spec and returns the id of a level at that rank
// (and the rank), opening a gap upward first when the target integer is already taken.
func (d *DB) resolveLevelTx(ctx context.Context, tx *sql.Tx, spec SignificanceSpec) (sql.NullInt64, int32, error) {
	if spec.Placement == PlacementNone {
		id, err := d.findOrCreateLevelTx(ctx, tx, spec.Value)

		return nullInt64(id), spec.Value, err
	}

	anchor, err := d.anchorRank(ctx, tx, spec.Anchor, spec.AnchorID, spec.AnchorKind)
	if err != nil {
		return sql.NullInt64{}, 0, err
	}

	target := int32(0)

	switch spec.Placement {

	case PlacementAbove:
		target = anchor + 1

	case PlacementBelow:
		target = anchor

	case PlacementBetween:
		upper, err := d.anchorRank(ctx, tx, spec.Upper, spec.UpperID, spec.UpperKind)
		if err != nil {
			return sql.NullInt64{}, 0, err
		}

		if upper <= anchor {
			return sql.NullInt64{}, 0, fmt.Errorf("%w: between upper bound %d must be greater than lower bound %d", ErrInvalidPlacement, upper, anchor)
		}

		// Prefer a free integer strictly inside (anchor, upper); if the bounds are adjacent, open a
		// gap just above the lower bound.
		target = anchor + 1
	}

	if target < 1 {
		target = 1
	}

	taken, err := d.rankTaken(ctx, tx, target)
	if err != nil {
		return sql.NullInt64{}, 0, err
	}

	if taken {
		if err := d.openGapAt(ctx, tx, target); err != nil {
			return sql.NullInt64{}, 0, err
		}
	}

	id, err := d.createLevelTx(ctx, tx, target)

	return nullInt64(id), target, err
}

// anchorRank returns the rank an anchor refers to: an item's current rank when an id is given,
// otherwise the literal value. An unknown id, or an id whose item is unranked, is an error - there
// is nothing to sit beside.
func (d *DB) anchorRank(ctx context.Context, tx *sql.Tx, value int32, id string, kind AnchorKind) (int32, error) {
	if id == "" {
		if value < 1 {
			return 0, fmt.Errorf("%w: anchor must be a positive value or an item id", ErrInvalidPlacement)
		}

		return value, nil
	}

	table := "memories"
	if kind == AnchorEvent {
		table = "events"
	}

	var rank sql.NullInt64

	query := d.rebind(`SELECT l.level_rank FROM ` + table + ` t
		LEFT JOIN significance_levels l ON l.id = t.significance_level_id
		WHERE t.id = ?`)

	if err := tx.QueryRowContext(ctx, query, id).Scan(&rank); err != nil {
		if err == sql.ErrNoRows {
			return 0, fmt.Errorf("%w: anchor %s '%s' not found", ErrInvalidPlacement, table, id)
		}

		return 0, err
	}

	if !rank.Valid {
		return 0, fmt.Errorf("%w: anchor %s '%s' is unranked", ErrInvalidPlacement, table, id)
	}

	return int32(rank.Int64), nil
}

// rankTaken reports whether a level already occupies the given rank.
func (d *DB) rankTaken(ctx context.Context, tx *sql.Tx, rank int32) (bool, error) {
	var exists bool

	query := d.rebind(`SELECT EXISTS(SELECT 1 FROM significance_levels WHERE level_rank = ?)`)

	if err := tx.QueryRowContext(ctx, query, rank).Scan(&exists); err != nil {
		return false, err
	}

	return exists, nil
}

// openGapAt frees the given rank by shifting every level at or above it up by one - a cheap update
// of the small registry that every item pointing at a bumped level follows automatically. It runs
// in two phases through negative space so the rank UNIQUE constraint is never transiently violated:
// a plain `rank = rank + 1 WHERE rank >= ?` collides when the ranks above the target are consecutive
// (SQLite checks uniqueness per row as it updates 6->7 while 7 still exists). Phase one moves the
// affected rows to distinct negatives preserving order; phase two flips them back, one higher.
func (d *DB) openGapAt(ctx context.Context, tx *sql.Tx, rank int32) error {
	if _, err := tx.ExecContext(ctx, d.rebind(`UPDATE significance_levels SET level_rank = -(level_rank + 1) WHERE level_rank >= ?`), rank); err != nil {
		return err
	}

	_, err := tx.ExecContext(ctx, `UPDATE significance_levels SET level_rank = -level_rank WHERE level_rank < 0`)

	return err
}

// findLevel looks up the level id for a rank without any lock (a plain indexed read), backing the
// ResolveSignificanceLevel fast path for already-known ranks.
func (d *DB) findLevel(ctx context.Context, rank int32) (int64, bool, error) {
	ctx, cancel := d.opContext(ctx)
	defer cancel()

	var id int64

	err := d.queryRow(ctx, `SELECT id FROM significance_levels WHERE level_rank = ?`, rank).Scan(&id)
	if err == sql.ErrNoRows {
		return 0, false, nil
	}

	if err != nil {
		return 0, false, err
	}

	return id, true, nil
}

// ensureSignificanceLevel resolves an absolute significance to a level id when the caller has not
// already supplied one (the RPC layer supplies it for placements; direct callers - tests, nested
// creates, and the ordinary absolute-significance path - do not). A non-positive significance stays
// unranked (nil).
func (d *DB) ensureSignificanceLevel(ctx context.Context, significance int32, levelID *int64) (*int64, error) {
	if levelID != nil || significance <= 0 {
		return levelID, nil
	}

	id, _, err := d.ResolveSignificanceLevel(ctx, SignificanceSpec{Value: significance})
	if err != nil {
		return nil, err
	}

	if id.Valid {
		v := id.Int64

		return &v, nil
	}

	return nil, nil
}

// findOrCreateLevelTx returns the id of the level at the given rank, creating it if absent.
func (d *DB) findOrCreateLevelTx(ctx context.Context, tx *sql.Tx, rank int32) (int64, error) {
	var id int64

	query := d.rebind(`SELECT id FROM significance_levels WHERE level_rank = ?`)

	err := tx.QueryRowContext(ctx, query, rank).Scan(&id)
	if err == nil {
		return id, nil
	}

	if err != sql.ErrNoRows {
		return 0, err
	}

	return d.createLevelTx(ctx, tx, rank)
}

// createLevelTx inserts a new level at the given rank and returns its id. lastInsertId is not
// portable (Postgres has no LastInsertId), so the id is read back by rank, which is UNIQUE.
func (d *DB) createLevelTx(ctx context.Context, tx *sql.Tx, rank int32) (int64, error) {
	insert := d.rebind(`INSERT INTO significance_levels (level_rank) VALUES (?)`)

	if _, err := tx.ExecContext(ctx, insert, rank); err != nil {
		return 0, err
	}

	var id int64

	if err := tx.QueryRowContext(ctx, d.rebind(`SELECT id FROM significance_levels WHERE level_rank = ?`), rank).Scan(&id); err != nil {
		return 0, err
	}

	return id, nil
}

// nullInt64 wraps a valid level id.
func nullInt64(id int64) sql.NullInt64 {
	return sql.NullInt64{Int64: id, Valid: true}
}

// registryAdvisoryLockKey is the Postgres advisory-lock key serializing registry renumbering,
// distinct from the single-consolidator instance lock (advisoryLockKey) so the two never contend.
const registryAdvisoryLockKey = advisoryLockKey + 1

// acquireRegistryLock serializes registry renumbering across instances on the server drivers, so
// two replicas cannot open a gap (shift ranks) at the same time. It holds the lock on a dedicated
// connection and returns a release function. SQLite needs none - its single connection already
// serializes every writer - so it returns a no-op.
func (d *DB) acquireRegistryLock(ctx context.Context) (func(), error) {
	if d.driver == driverSQLite {
		return func() {}, nil
	}

	conn, err := d.sql.Conn(ctx)
	if err != nil {
		return nil, err
	}

	switch d.driver {

	case driverPostgres:
		if _, err := conn.ExecContext(ctx, `SELECT pg_advisory_lock($1)`, registryAdvisoryLockKey); err != nil {
			_ = conn.Close()

			return nil, err
		}

		return func() {
			_, _ = conn.ExecContext(context.Background(), `SELECT pg_advisory_unlock($1)`, registryAdvisoryLockKey)
			_ = conn.Close()
		}, nil

	case driverMySQL:
		if _, err := conn.ExecContext(ctx, `SELECT GET_LOCK(CONCAT('hippocampus:registry:', DATABASE()), 10)`); err != nil {
			_ = conn.Close()

			return nil, err
		}

		return func() {
			_, _ = conn.ExecContext(context.Background(), `SELECT RELEASE_LOCK(CONCAT('hippocampus:registry:', DATABASE()))`)
			_ = conn.Close()
		}, nil
	}

	_ = conn.Close()

	return func() {}, nil
}

// registryCompactionThreshold is the maximum rank tolerated before compactSignificanceLevels
// renumbers the registry back to 1..N. Ranks stay dense in normal use (opening a gap between
// adjacent values keeps them consecutive), so this is a safety net against pathological inflation
// approaching the int32 ceiling rather than a routine operation.
const registryCompactionThreshold = int32(1) << 30

// CompactSignificanceLevels renumbers the registry to consecutive ranks 1..N preserving order, so
// ranks stay inside int32 after repeated upward gap-opening. It rewrites only the small registry;
// items follow their level id. It changes the absolute significance numbers clients see - which are
// relative ranks by design - so it runs only when the top rank crosses registryCompactionThreshold,
// on the consolidating instance (called best-effort from the sleep cycle). Renumbering routes
// through temporary negative ranks so the UNIQUE constraint is never transiently violated.
func (d *DB) CompactSignificanceLevels(ctx context.Context) error {
	log.Trace("func() db.CompactSignificanceLevels")

	var maxRank sql.NullInt64

	rankCtx, cancel := d.opContext(ctx)

	if err := d.queryRow(rankCtx, `SELECT MAX(level_rank) FROM significance_levels`).Scan(&maxRank); err != nil {
		cancel()

		return err
	}

	cancel()

	if !maxRank.Valid || int32(maxRank.Int64) < registryCompactionThreshold {
		return nil
	}

	log.Infof("compacting significance registry (top rank %d)", maxRank.Int64)

	release, err := d.acquireRegistryLock(ctx)
	if err != nil {
		return err
	}

	defer release()

	tx, txCancel, err := d.beginTx(ctx)
	if err != nil {
		return err
	}

	defer txCancel()

	rows, err := tx.QueryContext(ctx, `SELECT id FROM significance_levels ORDER BY level_rank ASC`)
	if err != nil {
		_ = tx.Rollback()

		return err
	}

	var ids []int64

	for rows.Next() {
		var id int64

		if err := rows.Scan(&id); err != nil {
			_ = rows.Close()
			_ = tx.Rollback()

			return err
		}

		ids = append(ids, id)
	}

	if err := rows.Err(); err != nil {
		_ = rows.Close()
		_ = tx.Rollback()

		return err
	}

	_ = rows.Close()

	update := d.rebind(`UPDATE significance_levels SET level_rank = ? WHERE id = ?`)

	for i, id := range ids {
		if _, err := tx.ExecContext(ctx, update, -(int32(i) + 1), id); err != nil {
			_ = tx.Rollback()

			return err
		}
	}

	if _, err := tx.ExecContext(ctx, `UPDATE significance_levels SET level_rank = -level_rank WHERE level_rank < 0`); err != nil {
		_ = tx.Rollback()

		return err
	}

	return tx.Commit()
}
